// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApproval = `-- name: GetApproval :one
SELECT id, type, facility_id, amount, title, context, requested_by,
       status, decided_at, decision_note, created_at
FROM approvals
WHERE id = $1
`

func (q *Queries) GetApproval(ctx context.Context, id string) (Approval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.FacilityID,
		&i.Amount,
		&i.Title,
		&i.Context,
		&i.RequestedBy,
		&i.Status,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovals = `-- name: ListApprovals :many
SELECT id, type, facility_id, amount, title, context, requested_by,
       status, decided_at, decision_note, created_at
FROM approvals
ORDER BY created_at, id
`

func (q *Queries) ListApprovals(ctx context.Context) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Approval
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FacilityID,
			&i.Amount,
			&i.Title,
			&i.Context,
			&i.RequestedBy,
			&i.Status,
			&i.DecidedAt,
			&i.DecisionNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApproval = `-- name: UpsertApproval :exec
INSERT INTO approvals (
    id, type, facility_id, amount, title, context, requested_by,
    status, decided_at, decision_note, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type,
    facility_id = EXCLUDED.facility_id,
    amount = EXCLUDED.amount,
    title = EXCLUDED.title,
    context = EXCLUDED.context,
    requested_by = EXCLUDED.requested_by,
    status = EXCLUDED.status,
    decided_at = EXCLUDED.decided_at,
    decision_note = EXCLUDED.decision_note,
    created_at = EXCLUDED.created_at
`

type UpsertApprovalParams struct {
	ID           string
	Type         string
	FacilityID   *string
	Amount       int64
	Title        string
	Context      string
	RequestedBy  string
	Status       string
	DecidedAt    pgtype.Timestamptz
	DecisionNote string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertApproval(ctx context.Context, arg UpsertApprovalParams) error {
	_, err := q.db.Exec(ctx, upsertApproval,
		arg.ID,
		arg.Type,
		arg.FacilityID,
		arg.Amount,
		arg.Title,
		arg.Context,
		arg.RequestedBy,
		arg.Status,
		arg.DecidedAt,
		arg.DecisionNote,
		arg.CreatedAt,
	)
	return err
}
