// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
DELETE FROM refresh_tokens
WHERE token_hash = $1
RETURNING user_id, name, role, facility_id, expires_at
`

type ConsumeRefreshTokenRow struct {
	UserID     string
	Name       string
	Role       string
	FacilityID string
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash string) (ConsumeRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var i ConsumeRefreshTokenRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Role,
		&i.FacilityID,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	return err
}

const findAccountByEmail = `-- name: FindAccountByEmail :one
SELECT u.id, u.name, u.role, u.facility_id, u.preferences,
       c.email, c.password_hash, c.mfa_secret
FROM credentials c
JOIN users u ON u.id = c.user_id
WHERE c.email = $1
`

type FindAccountByEmailRow struct {
	ID           string
	Name         string
	Role         string
	FacilityID   *string
	Preferences  []byte
	Email        string
	PasswordHash string
	MfaSecret    string
}

func (q *Queries) FindAccountByEmail(ctx context.Context, email string) (FindAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, findAccountByEmail, email)
	var i FindAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.FacilityID,
		&i.Preferences,
		&i.Email,
		&i.PasswordHash,
		&i.MfaSecret,
	)
	return i, err
}

const findAccountByID = `-- name: FindAccountByID :one
SELECT u.id, u.name, u.role, u.facility_id, u.preferences,
       c.email, c.password_hash, c.mfa_secret
FROM users u
JOIN credentials c ON c.user_id = u.id
WHERE u.id = $1
`

type FindAccountByIDRow struct {
	ID           string
	Name         string
	Role         string
	FacilityID   *string
	Preferences  []byte
	Email        string
	PasswordHash string
	MfaSecret    string
}

func (q *Queries) FindAccountByID(ctx context.Context, id string) (FindAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, findAccountByID, id)
	var i FindAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.FacilityID,
		&i.Preferences,
		&i.Email,
		&i.PasswordHash,
		&i.MfaSecret,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (token_hash, user_id, name, role, facility_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRefreshTokenParams struct {
	TokenHash  string
	UserID     string
	Name       string
	Role       string
	FacilityID string
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.TokenHash,
		arg.UserID,
		arg.Name,
		arg.Role,
		arg.FacilityID,
		arg.ExpiresAt,
	)
	return err
}

const upsertCredentials = `-- name: UpsertCredentials :exec
INSERT INTO credentials (user_id, email, password_hash, mfa_secret)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash,
    mfa_secret = EXCLUDED.mfa_secret,
    updated_at = now()
`

type UpsertCredentialsParams struct {
	UserID       string
	Email        string
	PasswordHash string
	MfaSecret    string
}

func (q *Queries) UpsertCredentials(ctx context.Context, arg UpsertCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertCredentials,
		arg.UserID,
		arg.Email,
		arg.PasswordHash,
		arg.MfaSecret,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, name, role, facility_id, preferences)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    role = EXCLUDED.role,
    facility_id = EXCLUDED.facility_id,
    preferences = EXCLUDED.preferences
`

type UpsertUserParams struct {
	ID          string
	Name        string
	Role        string
	FacilityID  *string
	Preferences []byte
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.FacilityID,
		arg.Preferences,
	)
	return err
}
