// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facility.sql

package sqlcgen

import (
	"context"
)

const createFacility = `-- name: CreateFacility :exec
INSERT INTO facilities (
    id, name, region, town, type, beds, lifecycle, health,
    manager_name, payer_nhis, payer_cash_momo, payer_private, latitude, longitude
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateFacilityParams struct {
	ID            string
	Name          string
	Region        string
	Town          string
	Type          string
	Beds          int32
	Lifecycle     string
	Health        string
	ManagerName   string
	PayerNhis     int16
	PayerCashMomo int16
	PayerPrivate  int16
	Latitude      float64
	Longitude     float64
}

func (q *Queries) CreateFacility(ctx context.Context, arg CreateFacilityParams) error {
	_, err := q.db.Exec(ctx, createFacility,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.Town,
		arg.Type,
		arg.Beds,
		arg.Lifecycle,
		arg.Health,
		arg.ManagerName,
		arg.PayerNhis,
		arg.PayerCashMomo,
		arg.PayerPrivate,
		arg.Latitude,
		arg.Longitude,
	)
	return err
}

const listFacilities = `-- name: ListFacilities :many
SELECT id, name, region, town, type, beds, lifecycle, health,
       manager_name, payer_nhis, payer_cash_momo, payer_private,
       latitude, longitude
FROM facilities
ORDER BY name
`

type ListFacilitiesRow struct {
	ID            string
	Name          string
	Region        string
	Town          string
	Type          string
	Beds          int32
	Lifecycle     string
	Health        string
	ManagerName   string
	PayerNhis     int16
	PayerCashMomo int16
	PayerPrivate  int16
	Latitude      float64
	Longitude     float64
}

func (q *Queries) ListFacilities(ctx context.Context) ([]ListFacilitiesRow, error) {
	rows, err := q.db.Query(ctx, listFacilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFacilitiesRow
	for rows.Next() {
		var i ListFacilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.Town,
			&i.Type,
			&i.Beds,
			&i.Lifecycle,
			&i.Health,
			&i.ManagerName,
			&i.PayerNhis,
			&i.PayerCashMomo,
			&i.PayerPrivate,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
