// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metric.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFacilityMetric = `-- name: InsertFacilityMetric :exec
INSERT INTO facility_metrics (
    facility_id, metric_date, revenue, cash_revenue, momo_revenue,
    patients_seen, admissions, occupancy_rate, avg_wait_minutes,
    nhis_claims_submitted, nhis_claims_paid, nhis_claims_denied,
    nhis_outstanding, unbilled_amount
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (facility_id, metric_date) DO UPDATE SET
    revenue = EXCLUDED.revenue,
    cash_revenue = EXCLUDED.cash_revenue,
    momo_revenue = EXCLUDED.momo_revenue,
    patients_seen = EXCLUDED.patients_seen,
    admissions = EXCLUDED.admissions,
    occupancy_rate = EXCLUDED.occupancy_rate,
    avg_wait_minutes = EXCLUDED.avg_wait_minutes,
    nhis_claims_submitted = EXCLUDED.nhis_claims_submitted,
    nhis_claims_paid = EXCLUDED.nhis_claims_paid,
    nhis_claims_denied = EXCLUDED.nhis_claims_denied,
    nhis_outstanding = EXCLUDED.nhis_outstanding,
    unbilled_amount = EXCLUDED.unbilled_amount
`

type InsertFacilityMetricParams struct {
	FacilityID          string
	MetricDate          pgtype.Date
	Revenue             int64
	CashRevenue         int64
	MomoRevenue         int64
	PatientsSeen        int32
	Admissions          int32
	OccupancyRate       float64
	AvgWaitMinutes      int32
	NhisClaimsSubmitted int32
	NhisClaimsPaid      int32
	NhisClaimsDenied    int32
	NhisOutstanding     int64
	UnbilledAmount      int64
}

func (q *Queries) InsertFacilityMetric(ctx context.Context, arg InsertFacilityMetricParams) error {
	_, err := q.db.Exec(ctx, insertFacilityMetric,
		arg.FacilityID,
		arg.MetricDate,
		arg.Revenue,
		arg.CashRevenue,
		arg.MomoRevenue,
		arg.PatientsSeen,
		arg.Admissions,
		arg.OccupancyRate,
		arg.AvgWaitMinutes,
		arg.NhisClaimsSubmitted,
		arg.NhisClaimsPaid,
		arg.NhisClaimsDenied,
		arg.NhisOutstanding,
		arg.UnbilledAmount,
	)
	return err
}

const listFacilityMetricsSince = `-- name: ListFacilityMetricsSince :many
SELECT facility_id, metric_date, revenue, cash_revenue, momo_revenue,
       patients_seen, admissions, occupancy_rate, avg_wait_minutes,
       nhis_claims_submitted, nhis_claims_paid, nhis_claims_denied,
       nhis_outstanding, unbilled_amount
FROM facility_metrics
WHERE facility_id = $1 AND metric_date >= $2
ORDER BY metric_date
`

type ListFacilityMetricsSinceParams struct {
	FacilityID string
	MetricDate pgtype.Date
}

func (q *Queries) ListFacilityMetricsSince(ctx context.Context, arg ListFacilityMetricsSinceParams) ([]FacilityMetric, error) {
	rows, err := q.db.Query(ctx, listFacilityMetricsSince, arg.FacilityID, arg.MetricDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacilityMetric
	for rows.Next() {
		var i FacilityMetric
		if err := rows.Scan(
			&i.FacilityID,
			&i.MetricDate,
			&i.Revenue,
			&i.CashRevenue,
			&i.MomoRevenue,
			&i.PatientsSeen,
			&i.Admissions,
			&i.OccupancyRate,
			&i.AvgWaitMinutes,
			&i.NhisClaimsSubmitted,
			&i.NhisClaimsPaid,
			&i.NhisClaimsDenied,
			&i.NhisOutstanding,
			&i.UnbilledAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworkMetrics = `-- name: ListNetworkMetrics :many
SELECT facility_id, metric_date, revenue, cash_revenue, momo_revenue,
       patients_seen, admissions, occupancy_rate, avg_wait_minutes,
       nhis_claims_submitted, nhis_claims_paid, nhis_claims_denied,
       nhis_outstanding, unbilled_amount
FROM facility_metrics
ORDER BY facility_id, metric_date
`

func (q *Queries) ListNetworkMetrics(ctx context.Context) ([]FacilityMetric, error) {
	rows, err := q.db.Query(ctx, listNetworkMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacilityMetric
	for rows.Next() {
		var i FacilityMetric
		if err := rows.Scan(
			&i.FacilityID,
			&i.MetricDate,
			&i.Revenue,
			&i.CashRevenue,
			&i.MomoRevenue,
			&i.PatientsSeen,
			&i.Admissions,
			&i.OccupancyRate,
			&i.AvgWaitMinutes,
			&i.NhisClaimsSubmitted,
			&i.NhisClaimsPaid,
			&i.NhisClaimsDenied,
			&i.NhisOutstanding,
			&i.UnbilledAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
