// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID                string
	FacilityID        string
	Type              string
	Severity          string
	Title             string
	Detail            string
	SupportingFigures []byte
	Status            string
	CreatedAt         pgtype.Timestamptz
}

type Approval struct {
	ID           string
	Type         string
	FacilityID   *string
	Amount       int64
	Title        string
	Context      string
	RequestedBy  string
	Status       string
	DecidedAt    pgtype.Timestamptz
	DecisionNote string
	CreatedAt    pgtype.Timestamptz
}

type Brief struct {
	ID              string
	BriefDate       pgtype.Date
	Prose           string
	Items           []byte
	GeneratedAt     pgtype.Timestamptz
	Model           string
	SourceSignalIds []string
}

type Credential struct {
	UserID       string
	Email        string
	PasswordHash string
	MfaSecret    string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Facility struct {
	ID            string
	Name          string
	Region        string
	Town          string
	Type          string
	Beds          int32
	Lifecycle     string
	Health        string
	ManagerName   string
	PayerNhis     int16
	PayerCashMomo int16
	PayerPrivate  int16
	Latitude      float64
	Longitude     float64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type FacilityMetric struct {
	FacilityID          string
	MetricDate          pgtype.Date
	Revenue             int64
	CashRevenue         int64
	MomoRevenue         int64
	PatientsSeen        int32
	Admissions          int32
	OccupancyRate       float64
	AvgWaitMinutes      int32
	NhisClaimsSubmitted int32
	NhisClaimsPaid      int32
	NhisClaimsDenied    int32
	NhisOutstanding     int64
	UnbilledAmount      int64
}

type Insight struct {
	ID                string
	Type              string
	FacilityID        *string
	Content           string
	SupportingFigures []byte
	GeneratedAt       pgtype.Timestamptz
}

type InventoryItem struct {
	ID           string
	FacilityID   string
	Name         string
	Category     string
	StockLevel   int32
	DailyBurn    float64
	ReorderPoint int32
	LeadTimeDays int32
	UnitCost     int64
}

type RefreshToken struct {
	TokenHash  string
	UserID     string
	Name       string
	Role       string
	FacilityID string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Staff struct {
	ID            string
	FacilityID    string
	Name          string
	Role          string
	LicenceNumber string
	LicenceExpiry pgtype.Date
	Status        string
	AttritionRisk float64
	JoinedDate    pgtype.Date
}

type Task struct {
	ID         string
	Title      string
	Detail     string
	FacilityID *string
	Priority   string
	Status     string
	DueDate    pgtype.Timestamptz
	AssignedTo string
	CreatedBy  string
	Source     string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID          string
	Name        string
	Role        string
	FacilityID  *string
	Preferences []byte
	CreatedAt   pgtype.Timestamptz
}
