// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTask = `-- name: GetTask :one
SELECT id, title, detail, facility_id, priority, status, due_date,
       assigned_to, created_by, source, created_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Detail,
		&i.FacilityID,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, detail, facility_id, priority, status, due_date,
       assigned_to, created_by, source, created_at
FROM tasks
ORDER BY created_at, id
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Detail,
			&i.FacilityID,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.AssignedTo,
			&i.CreatedBy,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTask = `-- name: UpsertTask :exec
INSERT INTO tasks (
    id, title, detail, facility_id, priority, status, due_date,
    assigned_to, created_by, source, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    detail = EXCLUDED.detail,
    facility_id = EXCLUDED.facility_id,
    priority = EXCLUDED.priority,
    status = EXCLUDED.status,
    due_date = EXCLUDED.due_date,
    assigned_to = EXCLUDED.assigned_to,
    created_by = EXCLUDED.created_by,
    source = EXCLUDED.source,
    created_at = EXCLUDED.created_at
`

type UpsertTaskParams struct {
	ID         string
	Title      string
	Detail     string
	FacilityID *string
	Priority   string
	Status     string
	DueDate    pgtype.Timestamptz
	AssignedTo string
	CreatedBy  string
	Source     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) error {
	_, err := q.db.Exec(ctx, upsertTask,
		arg.ID,
		arg.Title,
		arg.Detail,
		arg.FacilityID,
		arg.Priority,
		arg.Status,
		arg.DueDate,
		arg.AssignedTo,
		arg.CreatedBy,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}
