// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FacilityStatus.
const (
	Critical FacilityStatus = "critical"
	Good     FacilityStatus = "good"
	Watch    FacilityStatus = "watch"
)

// Valid indicates whether the value is a known member of the FacilityStatus enum.
func (e FacilityStatus) Valid() bool {
	switch e {
	case Critical:
		return true
	case Good:
		return true
	case Watch:
		return true
	default:
		return false
	}
}

// Defines values for KpiDirection.
const (
	Down KpiDirection = "down"
	Flat KpiDirection = "flat"
	Up   KpiDirection = "up"
)

// Valid indicates whether the value is a known member of the KpiDirection enum.
func (e KpiDirection) Valid() bool {
	switch e {
	case Down:
		return true
	case Flat:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for KpiUnit.
const (
	Count   KpiUnit = "count"
	Pesewas KpiUnit = "pesewas"
	Ratio   KpiUnit = "ratio"
)

// Valid indicates whether the value is a known member of the KpiUnit enum.
func (e KpiUnit) Valid() bool {
	switch e {
	case Count:
		return true
	case Pesewas:
		return true
	case Ratio:
		return true
	default:
		return false
	}
}

// Brief defines model for Brief.
type Brief struct {
	Date        openapi_types.Date `json:"date"`
	GeneratedAt *time.Time         `json:"generated_at,omitempty"`
	Id          string             `json:"id"`
	Items       []BriefItem        `json:"items"`
	Model       string             `json:"model"`
	Prose       string             `json:"prose"`
}

// BriefItem defines model for BriefItem.
type BriefItem struct {
	Explanation *string `json:"explanation,omitempty"`
	FacilityId  string  `json:"facility_id"`
	Headline    string  `json:"headline"`

	// Severity AI-assessed operational health signal.
	Severity         FacilityStatus `json:"severity"`
	SuggestedActions *[]string      `json:"suggested_actions,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Facility defines model for Facility.
type Facility struct {
	Beds   int32  `json:"beds"`
	Id     string `json:"id"`
	Name   string `json:"name"`
	Region string `json:"region"`

	// Status AI-assessed operational health signal.
	Status FacilityStatus `json:"status"`
	Town   string         `json:"town"`
}

// FacilityList defines model for FacilityList.
type FacilityList struct {
	Facilities []Facility `json:"facilities"`
}

// FacilityStatus AI-assessed operational health signal.
type FacilityStatus string

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Kpi defines model for Kpi.
type Kpi struct {
	Current        float64       `json:"current"`
	DeltaPct       float64       `json:"delta_pct"`
	Direction      KpiDirection  `json:"direction"`
	HigherIsBetter bool          `json:"higher_is_better"`
	Key            string        `json:"key"`
	Label          string        `json:"label"`
	Previous       float64       `json:"previous"`
	Series         []MetricPoint `json:"series"`
	Unit           KpiUnit       `json:"unit"`
}

// KpiDirection defines model for Kpi.Direction.
type KpiDirection string

// KpiUnit defines model for Kpi.Unit.
type KpiUnit string

// MetricPoint defines model for MetricPoint.
type MetricPoint struct {
	Date  openapi_types.Date `json:"date"`
	Value float64            `json:"value"`
}

// NetworkMetrics defines model for NetworkMetrics.
type NetworkMetrics struct {
	AsOf openapi_types.Date `json:"as_of"`
	Kpis []Kpi              `json:"kpis"`
}

// InternalError defines model for InternalError.
type InternalError = Error

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// The AI-narrated Daily Brief over the current network
	// (GET /api/v1/brief)
	GetBrief(w http.ResponseWriter, r *http.Request)
	// List all facilities in the network
	// (GET /api/v1/facilities)
	ListFacilities(w http.ResponseWriter, r *http.Request)
	// Deterministic network KPIs and weekly trends
	// (GET /api/v1/metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// The AI-narrated Daily Brief over the current network
// (GET /api/v1/brief)
func (_ Unimplemented) GetBrief(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all facilities in the network
// (GET /api/v1/facilities)
func (_ Unimplemented) ListFacilities(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deterministic network KPIs and weekly trends
// (GET /api/v1/metrics)
func (_ Unimplemented) GetMetrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBrief operation middleware
func (siw *ServerInterfaceWrapper) GetBrief(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBrief(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFacilities operation middleware
func (siw *ServerInterfaceWrapper) ListFacilities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFacilities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/brief", wrapper.GetBrief)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/facilities", wrapper.ListFacilities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/metrics", wrapper.GetMetrics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})

	return r
}

type InternalErrorJSONResponse Error

type GetBriefRequestObject struct {
}

type GetBriefResponseObject interface {
	VisitGetBriefResponse(w http.ResponseWriter) error
}

type GetBrief200JSONResponse Brief

func (response GetBrief200JSONResponse) VisitGetBriefResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBrief500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetBrief500JSONResponse) VisitGetBriefResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListFacilitiesRequestObject struct {
}

type ListFacilitiesResponseObject interface {
	VisitListFacilitiesResponse(w http.ResponseWriter) error
}

type ListFacilities200JSONResponse FacilityList

func (response ListFacilities200JSONResponse) VisitListFacilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListFacilities500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListFacilities500JSONResponse) VisitListFacilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetricsRequestObject struct {
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200JSONResponse NetworkMetrics

func (response GetMetrics200JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetrics500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMetrics500JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Health

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// The AI-narrated Daily Brief over the current network
	// (GET /api/v1/brief)
	GetBrief(ctx context.Context, request GetBriefRequestObject) (GetBriefResponseObject, error)
	// List all facilities in the network
	// (GET /api/v1/facilities)
	ListFacilities(ctx context.Context, request ListFacilitiesRequestObject) (ListFacilitiesResponseObject, error)
	// Deterministic network KPIs and weekly trends
	// (GET /api/v1/metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetBrief operation middleware
func (sh *strictHandler) GetBrief(w http.ResponseWriter, r *http.Request) {
	var request GetBriefRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBrief(ctx, request.(GetBriefRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBrief")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBriefResponseObject); ok {
		if err := validResponse.VisitGetBriefResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFacilities operation middleware
func (sh *strictHandler) ListFacilities(w http.ResponseWriter, r *http.Request) {
	var request ListFacilitiesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFacilities(ctx, request.(ListFacilitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFacilities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFacilitiesResponseObject); ok {
		if err := validResponse.VisitListFacilitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFdPk9u2D/0qHP5+h2RGtjfJ9OLbNn8aT9rOTp1bu+PAEiwhpkiVhOyoGX/3DkVJli3ZcTrZ01ok+PDw",
	"AILYrzI2eWE0anZy/lVadIXRDuuPhWa0GtRba431C7HRjJr9TygKRTEwGT377Iz2ay7OMAf/6/8WN3Iu",
	"/zc7os/CrpsFtMPhEMkEXWyp8CBy3rkTDu0OrcDGMGqAa04/W/LQX2VhTYGWKVBNgNH/3RibA8t5WIgk",
	"VwXKuXRsSafyEMkUNVpgTFbAgwMTpnz0FCXedrjMmNfuux/XAq+pLxhzf7TBAmuh8t+5SVCNOimscTiy",
	"c4ikxb9LspjI+Z+eYtRGHY60oC3Px86rWX/GmD34kdNAUvxSKNAQkjPCawMxKeJqdUGcDCFRpHF00+EO",
	"LXH1Lc3eNU6WDFy6+mSZpujqBMae26n+A0enOp9p1rE4jabHfUyz7jqc6dUuX89TMBvDbWMdQq8xcSfF",
	"SppfvTwWKmnGFO2VStWQjyfCYnopwS5o/t0ZYrPXN9ZrTasj0RyNQrwdgWta/UqOh3o1yWy+brqcnfjf",
	"qpke9jViy0680yZ3v5iAc+gcJsJTru8XKJEhKM6Eo1SDmspIoi5z7y81xiu1B44zGcnYElMMquf8mLH3",
	"NchQj2Mm8Qvkhaopb4eN7vx6XNb/Q0FDN3FpbfM8HNuqKdeq11N1ma9DpSaoGFZFfLM9WYzbbtSqUxa+",
	"64Wq2SjgUVkySjO0K3KrNTJj/5KujVEI2lttsRq9BgrWFzsz7siU7sYAHNrvqcjfkC3FD4Y0jz0YpSbu",
	"K1Ggwz34a1PXlC8VU+oxQc6y7ONuo2xgRySLuuz24u4nsZ+gLtax0unH9d/f8R2oEm8S/izcBjCcH+P3",
	"O/Le2G2g6YYUwa3M5iaO24JuT7e/Ud/qPcF1Azzk7s1Jb8yw6/zxdvlR3D8sxMZYwRmKXyjNQWvx9gvG",
	"JdMOxWsTbwviqXhtNFuIebIh63gezE07lPmnxm4gRidAJ/Xmx6rAZe1MxIpQswCLohu0xMaaXHBGTmxI",
	"oXj2KYftcf/T86l4Y4Q2LDLQyQQT4t7h2CQ4/at+G4jrxnWRug/QZxatC1HfTV9M77yopkANvmPJV9O7",
	"6StfwsBZnZIZFDTbvZit27kyxbosu968SLxP5DB4RqcT8su7ux82FwcHI3PxxwzFGyBVicYkkj8Fv2Nw",
	"Hb/Z6fhez9FlnoOtGsz7xUT7OvMy9/CF8Xn2iW1uvNDhRvgcQOp8IQa1Hj1mK+Dpmzuqon+s3x3NnlDL",
	"k/HggqQ9wj9CUe9KgFI9XEG61nGoX3+I6IuYH5vOpTps+9ITqnfWAUf0ayzEh4dF0wcs6uTHCPkGGW1O",
	"mhxT3Gp39LRH3KqqdXiUtJUu6BnGqX+uCfm+MXlCIZt5bETAJdodxSjINZNfNSinHWp0ThTWrLEXp6uc",
	"/3ftsQYNTdmvn3f8JeQ4MZZS0uJZbZaINWbU9Ozlw72Y1S9CCox7qJ77t98qOZczeXg8/BsAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
