// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApprovalStatus.
const (
	Approved ApprovalStatus = "approved"
	Declined ApprovalStatus = "declined"
	Pending  ApprovalStatus = "pending"
)

// Valid indicates whether the value is a known member of the ApprovalStatus enum.
func (e ApprovalStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Declined:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalType.
const (
	Capital ApprovalType = "capital"
	Hire    ApprovalType = "hire"
	Reorder ApprovalType = "reorder"
)

// Valid indicates whether the value is a known member of the ApprovalType enum.
func (e ApprovalType) Valid() bool {
	switch e {
	case Capital:
		return true
	case Hire:
		return true
	case Reorder:
		return true
	default:
		return false
	}
}

// Defines values for AuthUserRole.
const (
	Executive       AuthUserRole = "executive"
	FacilityManager AuthUserRole = "facility_manager"
)

// Valid indicates whether the value is a known member of the AuthUserRole enum.
func (e AuthUserRole) Valid() bool {
	switch e {
	case Executive:
		return true
	case FacilityManager:
		return true
	default:
		return false
	}
}

// Defines values for DecisionRequestDecision.
const (
	Approve DecisionRequestDecision = "approve"
	Decline DecisionRequestDecision = "decline"
)

// Valid indicates whether the value is a known member of the DecisionRequestDecision enum.
func (e DecisionRequestDecision) Valid() bool {
	switch e {
	case Approve:
		return true
	case Decline:
		return true
	default:
		return false
	}
}

// Defines values for FacilityStatus.
const (
	Critical FacilityStatus = "critical"
	Good     FacilityStatus = "good"
	Watch    FacilityStatus = "watch"
)

// Valid indicates whether the value is a known member of the FacilityStatus enum.
func (e FacilityStatus) Valid() bool {
	switch e {
	case Critical:
		return true
	case Good:
		return true
	case Watch:
		return true
	default:
		return false
	}
}

// Defines values for KpiDirection.
const (
	Down KpiDirection = "down"
	Flat KpiDirection = "flat"
	Up   KpiDirection = "up"
)

// Valid indicates whether the value is a known member of the KpiDirection enum.
func (e KpiDirection) Valid() bool {
	switch e {
	case Down:
		return true
	case Flat:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for KpiUnit.
const (
	Count   KpiUnit = "count"
	Pesewas KpiUnit = "pesewas"
	Ratio   KpiUnit = "ratio"
)

// Valid indicates whether the value is a known member of the KpiUnit enum.
func (e KpiUnit) Valid() bool {
	switch e {
	case Count:
		return true
	case Pesewas:
		return true
	case Ratio:
		return true
	default:
		return false
	}
}

// Defines values for TaskPriority.
const (
	High   TaskPriority = "high"
	Low    TaskPriority = "low"
	Medium TaskPriority = "medium"
)

// Valid indicates whether the value is a known member of the TaskPriority enum.
func (e TaskPriority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for TaskSource.
const (
	TaskSourceAlert  TaskSource = "alert"
	TaskSourceBrief  TaskSource = "brief"
	TaskSourceManual TaskSource = "manual"
)

// Valid indicates whether the value is a known member of the TaskSource enum.
func (e TaskSource) Valid() bool {
	switch e {
	case TaskSourceAlert:
		return true
	case TaskSourceBrief:
		return true
	case TaskSourceManual:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusDone       TaskStatus = "done"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusTodo       TaskStatus = "todo"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusDone:
		return true
	case TaskStatusInProgress:
		return true
	case TaskStatusTodo:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatusRequestStatus.
const (
	TaskStatusRequestStatusDone       TaskStatusRequestStatus = "done"
	TaskStatusRequestStatusInProgress TaskStatusRequestStatus = "in_progress"
	TaskStatusRequestStatusTodo       TaskStatusRequestStatus = "todo"
)

// Valid indicates whether the value is a known member of the TaskStatusRequestStatus enum.
func (e TaskStatusRequestStatus) Valid() bool {
	switch e {
	case TaskStatusRequestStatusDone:
		return true
	case TaskStatusRequestStatusInProgress:
		return true
	case TaskStatusRequestStatusTodo:
		return true
	default:
		return false
	}
}

// AlertItem defines model for AlertItem.
type AlertItem struct {
	Detail *string `json:"detail,omitempty"`
	Id     string  `json:"id"`

	// Severity AI-assessed operational health signal.
	Severity FacilityStatus `json:"severity"`
	Status   string         `json:"status"`
	Title    string         `json:"title"`
	Type     string         `json:"type"`
}

// Answer defines model for Answer.
type Answer struct {
	Citations *[]string `json:"citations,omitempty"`
	Text      string    `json:"text"`
}

// Approval defines model for Approval.
type Approval struct {
	AmountPesewas int64          `json:"amount_pesewas"`
	Context       *string        `json:"context,omitempty"`
	CreatedAt     time.Time      `json:"created_at"`
	DecidedAt     *time.Time     `json:"decided_at,omitempty"`
	DecisionNote  *string        `json:"decision_note,omitempty"`
	FacilityId    string         `json:"facility_id"`
	Id            string         `json:"id"`
	RequestedBy   string         `json:"requested_by"`
	Status        ApprovalStatus `json:"status"`
	Title         string         `json:"title"`
	Type          ApprovalType   `json:"type"`
}

// ApprovalStatus defines model for Approval.Status.
type ApprovalStatus string

// ApprovalType defines model for Approval.Type.
type ApprovalType string

// ApprovalList defines model for ApprovalList.
type ApprovalList struct {
	Approvals []Approval `json:"approvals"`
}

// AskRequest defines model for AskRequest.
type AskRequest struct {
	Question string `json:"question"`
}

// AuthSession defines model for AuthSession.
type AuthSession struct {
	RefreshToken string   `json:"refresh_token"`
	Token        string   `json:"token"`
	User         AuthUser `json:"user"`
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	FacilityId *string      `json:"facility_id,omitempty"`
	Id         string       `json:"id"`
	Name       string       `json:"name"`
	Role       AuthUserRole `json:"role"`
}

// AuthUserRole defines model for AuthUser.Role.
type AuthUserRole string

// Brief defines model for Brief.
type Brief struct {
	Date        openapi_types.Date `json:"date"`
	GeneratedAt *time.Time         `json:"generated_at,omitempty"`
	Id          string             `json:"id"`
	Items       []BriefItem        `json:"items"`
	Model       string             `json:"model"`
	Prose       string             `json:"prose"`
}

// BriefItem defines model for BriefItem.
type BriefItem struct {
	Explanation *string `json:"explanation,omitempty"`
	FacilityId  string  `json:"facility_id"`
	Headline    string  `json:"headline"`

	// Severity AI-assessed operational health signal.
	Severity         FacilityStatus `json:"severity"`
	SuggestedActions *[]string      `json:"suggested_actions,omitempty"`
}

// DecisionRequest defines model for DecisionRequest.
type DecisionRequest struct {
	Decision DecisionRequestDecision `json:"decision"`
	Note     *string                 `json:"note,omitempty"`
}

// DecisionRequestDecision defines model for DecisionRequest.Decision.
type DecisionRequestDecision string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Facility defines model for Facility.
type Facility struct {
	Beds   int32  `json:"beds"`
	Id     string `json:"id"`
	Name   string `json:"name"`
	Region string `json:"region"`

	// Status AI-assessed operational health signal.
	Status FacilityStatus `json:"status"`
	Town   string         `json:"town"`
}

// FacilityDetail defines model for FacilityDetail.
type FacilityDetail struct {
	Alerts    []AlertItem     `json:"alerts"`
	Facility  Facility        `json:"facility"`
	Inventory []InventoryItem `json:"inventory"`
	Staff     []StaffMember   `json:"staff"`
}

// FacilityList defines model for FacilityList.
type FacilityList struct {
	Facilities []Facility `json:"facilities"`
}

// FacilityMatch defines model for FacilityMatch.
type FacilityMatch struct {
	FacilityId string `json:"facilityId"`
	Name       string `json:"name"`

	// Score Cosine similarity in [0,1]; 1 is identical.
	Score float64 `json:"score"`
}

// FacilitySearchResults defines model for FacilitySearchResults.
type FacilitySearchResults struct {
	Matches []FacilityMatch `json:"matches"`
	Query   string          `json:"query"`
}

// FacilityStatus AI-assessed operational health signal.
type FacilityStatus string

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// InventoryItem defines model for InventoryItem.
type InventoryItem struct {
	Category         string   `json:"category"`
	DaysOfStock      *float64 `json:"days_of_stock,omitempty"`
	Id               string   `json:"id"`
	Name             string   `json:"name"`
	StockLevel       int32    `json:"stock_level"`
	StockoutImminent bool     `json:"stockout_imminent"`
}

// Kpi defines model for Kpi.
type Kpi struct {
	Current        float64       `json:"current"`
	DeltaPct       float64       `json:"delta_pct"`
	Direction      KpiDirection  `json:"direction"`
	HigherIsBetter bool          `json:"higher_is_better"`
	Key            string        `json:"key"`
	Label          string        `json:"label"`
	Previous       float64       `json:"previous"`
	Series         []MetricPoint `json:"series"`
	Unit           KpiUnit       `json:"unit"`
}

// KpiDirection defines model for Kpi.Direction.
type KpiDirection string

// KpiUnit defines model for Kpi.Unit.
type KpiUnit string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Code     *string `json:"code,omitempty"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
}

// MetricPoint defines model for MetricPoint.
type MetricPoint struct {
	Date  openapi_types.Date `json:"date"`
	Value float64            `json:"value"`
}

// MfaConfirmRequest defines model for MfaConfirmRequest.
type MfaConfirmRequest struct {
	Code   string `json:"code"`
	Secret string `json:"secret"`
}

// MfaEnrollment defines model for MfaEnrollment.
type MfaEnrollment struct {
	OtpauthUri string `json:"otpauth_uri"`
	Secret     string `json:"secret"`
}

// NetworkMetrics defines model for NetworkMetrics.
type NetworkMetrics struct {
	AsOf openapi_types.Date `json:"as_of"`
	Kpis []Kpi              `json:"kpis"`
}

// Preferences defines model for Preferences.
type Preferences struct {
	Thresholds     map[string]float64 `json:"thresholds"`
	WatchedMetrics []string           `json:"watched_metrics"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// StaffMember defines model for StaffMember.
type StaffMember struct {
	AttritionRisk float64             `json:"attrition_risk"`
	Id            string              `json:"id"`
	LicenceExpiry *openapi_types.Date `json:"licence_expiry,omitempty"`
	Name          string              `json:"name"`
	Role          string              `json:"role"`
	Status        string              `json:"status"`
}

// Task defines model for Task.
type Task struct {
	AssignedTo *string             `json:"assigned_to,omitempty"`
	CreatedAt  time.Time           `json:"created_at"`
	Detail     *string             `json:"detail,omitempty"`
	DueDate    *openapi_types.Date `json:"due_date,omitempty"`
	FacilityId *string             `json:"facility_id,omitempty"`
	Id         string              `json:"id"`
	Priority   TaskPriority        `json:"priority"`
	Source     TaskSource          `json:"source"`
	Status     TaskStatus          `json:"status"`
	Title      string              `json:"title"`
}

// TaskPriority defines model for Task.Priority.
type TaskPriority string

// TaskSource defines model for Task.Source.
type TaskSource string

// TaskStatus defines model for Task.Status.
type TaskStatus string

// TaskList defines model for TaskList.
type TaskList struct {
	Tasks []Task `json:"tasks"`
}

// TaskStatusRequest defines model for TaskStatusRequest.
type TaskStatusRequest struct {
	Status TaskStatusRequestStatus `json:"status"`
}

// TaskStatusRequestStatus defines model for TaskStatusRequest.Status.
type TaskStatusRequestStatus string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// SearchFacilitiesParams defines parameters for SearchFacilities.
type SearchFacilitiesParams struct {
	Q     string `form:"q" json:"q"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// DecideApprovalJSONRequestBody defines body for DecideApproval for application/json ContentType.
type DecideApprovalJSONRequestBody = DecisionRequest

// PostAskJSONRequestBody defines body for PostAsk for application/json ContentType.
type PostAskJSONRequestBody = AskRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthLogoutJSONRequestBody defines body for PostAuthLogout for application/json ContentType.
type PostAuthLogoutJSONRequestBody = RefreshRequest

// PostAuthMfaConfirmJSONRequestBody defines body for PostAuthMfaConfirm for application/json ContentType.
type PostAuthMfaConfirmJSONRequestBody = MfaConfirmRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshRequest

// UpdateMePreferencesJSONRequestBody defines body for UpdateMePreferences for application/json ContentType.
type UpdateMePreferencesJSONRequestBody = Preferences

// UpdateTaskStatusJSONRequestBody defines body for UpdateTaskStatus for application/json ContentType.
type UpdateTaskStatusJSONRequestBody = TaskStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Approvals routed to the executive
	// (GET /api/v1/approvals)
	ListApprovals(w http.ResponseWriter, r *http.Request)
	// Approve or decline a pending approval (explicit, user-initiated)
	// (POST /api/v1/approvals/{approvalId}/decision)
	DecideApproval(w http.ResponseWriter, r *http.Request, approvalId string)
	// Ask a natural-language question about the network
	// (POST /api/v1/ask)
	PostAsk(w http.ResponseWriter, r *http.Request)
	// Exchange email and password for an access token
	// (POST /api/v1/auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Revoke a refresh token
	// (POST /api/v1/auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// The current authenticated user
	// (GET /api/v1/auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Confirm TOTP enrollment with a code
	// (POST /api/v1/auth/mfa/confirm)
	PostAuthMfaConfirm(w http.ResponseWriter, r *http.Request)
	// Begin TOTP enrollment (returns a secret + otpauth URI)
	// (POST /api/v1/auth/mfa/enroll)
	PostAuthMfaEnroll(w http.ResponseWriter, r *http.Request)
	// Rotate a refresh token into a new access + refresh token
	// (POST /api/v1/auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)
	// The AI-narrated Daily Brief over the current network
	// (GET /api/v1/brief)
	GetBrief(w http.ResponseWriter, r *http.Request)
	// List all facilities in the network
	// (GET /api/v1/facilities)
	ListFacilities(w http.ResponseWriter, r *http.Request)
	// Resolve a natural-language phrase to facilities via vector similarity
	// (GET /api/v1/facilities/search)
	SearchFacilities(w http.ResponseWriter, r *http.Request, params SearchFacilitiesParams)
	// Facility drill-down (inventory, staff, alerts)
	// (GET /api/v1/facilities/{facilityId})
	GetFacility(w http.ResponseWriter, r *http.Request, facilityId string)
	// The current user's personalisation preferences
	// (GET /api/v1/me/preferences)
	GetMePreferences(w http.ResponseWriter, r *http.Request)
	// Update the current user's personalisation preferences
	// (PATCH /api/v1/me/preferences)
	UpdateMePreferences(w http.ResponseWriter, r *http.Request)
	// Deterministic network KPIs and weekly trends
	// (GET /api/v1/metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
	// The executive's "My Day" tasks
	// (GET /api/v1/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request)
	// Update a task's status
	// (POST /api/v1/tasks/{taskId}/status)
	UpdateTaskStatus(w http.ResponseWriter, r *http.Request, taskId string)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Approvals routed to the executive
// (GET /api/v1/approvals)
func (_ Unimplemented) ListApprovals(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Approve or decline a pending approval (explicit, user-initiated)
// (POST /api/v1/approvals/{approvalId}/decision)
func (_ Unimplemented) DecideApproval(w http.ResponseWriter, r *http.Request, approvalId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ask a natural-language question about the network
// (POST /api/v1/ask)
func (_ Unimplemented) PostAsk(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange email and password for an access token
// (POST /api/v1/auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a refresh token
// (POST /api/v1/auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// The current authenticated user
// (GET /api/v1/auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm TOTP enrollment with a code
// (POST /api/v1/auth/mfa/confirm)
func (_ Unimplemented) PostAuthMfaConfirm(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Begin TOTP enrollment (returns a secret + otpauth URI)
// (POST /api/v1/auth/mfa/enroll)
func (_ Unimplemented) PostAuthMfaEnroll(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate a refresh token into a new access + refresh token
// (POST /api/v1/auth/refresh)
func (_ Unimplemented) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// The AI-narrated Daily Brief over the current network
// (GET /api/v1/brief)
func (_ Unimplemented) GetBrief(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all facilities in the network
// (GET /api/v1/facilities)
func (_ Unimplemented) ListFacilities(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resolve a natural-language phrase to facilities via vector similarity
// (GET /api/v1/facilities/search)
func (_ Unimplemented) SearchFacilities(w http.ResponseWriter, r *http.Request, params SearchFacilitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Facility drill-down (inventory, staff, alerts)
// (GET /api/v1/facilities/{facilityId})
func (_ Unimplemented) GetFacility(w http.ResponseWriter, r *http.Request, facilityId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// The current user's personalisation preferences
// (GET /api/v1/me/preferences)
func (_ Unimplemented) GetMePreferences(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update the current user's personalisation preferences
// (PATCH /api/v1/me/preferences)
func (_ Unimplemented) UpdateMePreferences(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deterministic network KPIs and weekly trends
// (GET /api/v1/metrics)
func (_ Unimplemented) GetMetrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// The executive's "My Day" tasks
// (GET /api/v1/tasks)
func (_ Unimplemented) ListTasks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a task's status
// (POST /api/v1/tasks/{taskId}/status)
func (_ Unimplemented) UpdateTaskStatus(w http.ResponseWriter, r *http.Request, taskId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApprovals operation middleware
func (siw *ServerInterfaceWrapper) ListApprovals(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApprovals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideApproval operation middleware
func (siw *ServerInterfaceWrapper) DecideApproval(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "approvalId" -------------
	var approvalId string

	err = runtime.BindStyledParameterWithOptions("simple", "approvalId", chi.URLParam(r, "approvalId"), &approvalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "approvalId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideApproval(w, r, approvalId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAsk operation middleware
func (siw *ServerInterfaceWrapper) PostAsk(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAsk(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthMfaConfirm operation middleware
func (siw *ServerInterfaceWrapper) PostAuthMfaConfirm(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthMfaConfirm(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthMfaEnroll operation middleware
func (siw *ServerInterfaceWrapper) PostAuthMfaEnroll(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthMfaEnroll(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBrief operation middleware
func (siw *ServerInterfaceWrapper) GetBrief(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBrief(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFacilities operation middleware
func (siw *ServerInterfaceWrapper) ListFacilities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFacilities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchFacilities operation middleware
func (siw *ServerInterfaceWrapper) SearchFacilities(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchFacilitiesParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchFacilities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFacility operation middleware
func (siw *ServerInterfaceWrapper) GetFacility(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "facilityId" -------------
	var facilityId string

	err = runtime.BindStyledParameterWithOptions("simple", "facilityId", chi.URLParam(r, "facilityId"), &facilityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "facilityId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFacility(w, r, facilityId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMePreferences operation middleware
func (siw *ServerInterfaceWrapper) GetMePreferences(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMePreferences(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMePreferences operation middleware
func (siw *ServerInterfaceWrapper) UpdateMePreferences(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMePreferences(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateTaskStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId string

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", chi.URLParam(r, "taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTaskStatus(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/approvals", wrapper.ListApprovals)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/approvals/{approvalId}/decision", wrapper.DecideApproval)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/ask", wrapper.PostAsk)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa/confirm", wrapper.PostAuthMfaConfirm)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa/enroll", wrapper.PostAuthMfaEnroll)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/refresh", wrapper.PostAuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/brief", wrapper.GetBrief)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/facilities", wrapper.ListFacilities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/facilities/search", wrapper.SearchFacilities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/facilities/{facilityId}", wrapper.GetFacility)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/me/preferences", wrapper.GetMePreferences)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/me/preferences", wrapper.UpdateMePreferences)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/metrics", wrapper.GetMetrics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tasks", wrapper.ListTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks/{taskId}/status", wrapper.UpdateTaskStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListApprovalsRequestObject struct {
}

type ListApprovalsResponseObject interface {
	VisitListApprovalsResponse(w http.ResponseWriter) error
}

type ListApprovals200JSONResponse ApprovalList

func (response ListApprovals200JSONResponse) VisitListApprovalsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListApprovals401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListApprovals401JSONResponse) VisitListApprovalsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListApprovals500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListApprovals500JSONResponse) VisitListApprovalsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DecideApprovalRequestObject struct {
	ApprovalId string `json:"approvalId"`
	Body       *DecideApprovalJSONRequestBody
}

type DecideApprovalResponseObject interface {
	VisitDecideApprovalResponse(w http.ResponseWriter) error
}

type DecideApproval200JSONResponse Approval

func (response DecideApproval200JSONResponse) VisitDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DecideApproval401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DecideApproval401JSONResponse) VisitDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DecideApproval403JSONResponse struct{ ForbiddenJSONResponse }

func (response DecideApproval403JSONResponse) VisitDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DecideApproval404JSONResponse struct{ NotFoundJSONResponse }

func (response DecideApproval404JSONResponse) VisitDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DecideApproval409JSONResponse struct{ ConflictJSONResponse }

func (response DecideApproval409JSONResponse) VisitDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DecideApproval500JSONResponse struct{ InternalErrorJSONResponse }

func (response DecideApproval500JSONResponse) VisitDecideApprovalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostAskRequestObject struct {
	Body *PostAskJSONRequestBody
}

type PostAskResponseObject interface {
	VisitPostAskResponse(w http.ResponseWriter) error
}

type PostAsk200JSONResponse Answer

func (response PostAsk200JSONResponse) VisitPostAskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAsk401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostAsk401JSONResponse) VisitPostAskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAsk500JSONResponse struct{ InternalErrorJSONResponse }

func (response PostAsk500JSONResponse) VisitPostAskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLoginRequestObject struct {
	Body *PostAuthLoginJSONRequestBody
}

type PostAuthLoginResponseObject interface {
	VisitPostAuthLoginResponse(w http.ResponseWriter) error
}

type PostAuthLogin200JSONResponse AuthSession

func (response PostAuthLogin200JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogin401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostAuthLogin401JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogoutRequestObject struct {
	Body *PostAuthLogoutJSONRequestBody
}

type PostAuthLogoutResponseObject interface {
	VisitPostAuthLogoutResponse(w http.ResponseWriter) error
}

type PostAuthLogout204Response struct {
}

func (response PostAuthLogout204Response) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetAuthMeRequestObject struct {
}

type GetAuthMeResponseObject interface {
	VisitGetAuthMeResponse(w http.ResponseWriter) error
}

type GetAuthMe200JSONResponse AuthUser

func (response GetAuthMe200JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAuthMe401JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthMfaConfirmRequestObject struct {
	Body *PostAuthMfaConfirmJSONRequestBody
}

type PostAuthMfaConfirmResponseObject interface {
	VisitPostAuthMfaConfirmResponse(w http.ResponseWriter) error
}

type PostAuthMfaConfirm204Response struct {
}

func (response PostAuthMfaConfirm204Response) VisitPostAuthMfaConfirmResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PostAuthMfaConfirm400JSONResponse struct{ BadRequestJSONResponse }

func (response PostAuthMfaConfirm400JSONResponse) VisitPostAuthMfaConfirmResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthMfaConfirm401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostAuthMfaConfirm401JSONResponse) VisitPostAuthMfaConfirmResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthMfaConfirm500JSONResponse struct{ InternalErrorJSONResponse }

func (response PostAuthMfaConfirm500JSONResponse) VisitPostAuthMfaConfirmResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthMfaEnrollRequestObject struct {
}

type PostAuthMfaEnrollResponseObject interface {
	VisitPostAuthMfaEnrollResponse(w http.ResponseWriter) error
}

type PostAuthMfaEnroll200JSONResponse MfaEnrollment

func (response PostAuthMfaEnroll200JSONResponse) VisitPostAuthMfaEnrollResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthMfaEnroll401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostAuthMfaEnroll401JSONResponse) VisitPostAuthMfaEnrollResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthMfaEnroll500JSONResponse struct{ InternalErrorJSONResponse }

func (response PostAuthMfaEnroll500JSONResponse) VisitPostAuthMfaEnrollResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRefreshRequestObject struct {
	Body *PostAuthRefreshJSONRequestBody
}

type PostAuthRefreshResponseObject interface {
	VisitPostAuthRefreshResponse(w http.ResponseWriter) error
}

type PostAuthRefresh200JSONResponse AuthSession

func (response PostAuthRefresh200JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthRefresh401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostAuthRefresh401JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetBriefRequestObject struct {
}

type GetBriefResponseObject interface {
	VisitGetBriefResponse(w http.ResponseWriter) error
}

type GetBrief200JSONResponse Brief

func (response GetBrief200JSONResponse) VisitGetBriefResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBrief500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetBrief500JSONResponse) VisitGetBriefResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListFacilitiesRequestObject struct {
}

type ListFacilitiesResponseObject interface {
	VisitListFacilitiesResponse(w http.ResponseWriter) error
}

type ListFacilities200JSONResponse FacilityList

func (response ListFacilities200JSONResponse) VisitListFacilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListFacilities500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListFacilities500JSONResponse) VisitListFacilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SearchFacilitiesRequestObject struct {
	Params SearchFacilitiesParams
}

type SearchFacilitiesResponseObject interface {
	VisitSearchFacilitiesResponse(w http.ResponseWriter) error
}

type SearchFacilities200JSONResponse FacilitySearchResults

func (response SearchFacilities200JSONResponse) VisitSearchFacilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchFacilities401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SearchFacilities401JSONResponse) VisitSearchFacilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SearchFacilities500JSONResponse struct{ InternalErrorJSONResponse }

func (response SearchFacilities500JSONResponse) VisitSearchFacilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetFacilityRequestObject struct {
	FacilityId string `json:"facilityId"`
}

type GetFacilityResponseObject interface {
	VisitGetFacilityResponse(w http.ResponseWriter) error
}

type GetFacility200JSONResponse FacilityDetail

func (response GetFacility200JSONResponse) VisitGetFacilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFacility401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetFacility401JSONResponse) VisitGetFacilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetFacility404JSONResponse struct{ NotFoundJSONResponse }

func (response GetFacility404JSONResponse) VisitGetFacilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetFacility500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetFacility500JSONResponse) VisitGetFacilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMePreferencesRequestObject struct {
}

type GetMePreferencesResponseObject interface {
	VisitGetMePreferencesResponse(w http.ResponseWriter) error
}

type GetMePreferences200JSONResponse Preferences

func (response GetMePreferences200JSONResponse) VisitGetMePreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMePreferences401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMePreferences401JSONResponse) VisitGetMePreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMePreferences500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMePreferences500JSONResponse) VisitGetMePreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMePreferencesRequestObject struct {
	Body *UpdateMePreferencesJSONRequestBody
}

type UpdateMePreferencesResponseObject interface {
	VisitUpdateMePreferencesResponse(w http.ResponseWriter) error
}

type UpdateMePreferences200JSONResponse Preferences

func (response UpdateMePreferences200JSONResponse) VisitUpdateMePreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMePreferences401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMePreferences401JSONResponse) VisitUpdateMePreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMePreferences500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateMePreferences500JSONResponse) VisitUpdateMePreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetricsRequestObject struct {
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200JSONResponse NetworkMetrics

func (response GetMetrics200JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetrics500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMetrics500JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListTasksRequestObject struct {
}

type ListTasksResponseObject interface {
	VisitListTasksResponse(w http.ResponseWriter) error
}

type ListTasks200JSONResponse TaskList

func (response ListTasks200JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTasks401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListTasks401JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListTasks500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListTasks500JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTaskStatusRequestObject struct {
	TaskId string `json:"taskId"`
	Body   *UpdateTaskStatusJSONRequestBody
}

type UpdateTaskStatusResponseObject interface {
	VisitUpdateTaskStatusResponse(w http.ResponseWriter) error
}

type UpdateTaskStatus200JSONResponse Task

func (response UpdateTaskStatus200JSONResponse) VisitUpdateTaskStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTaskStatus401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateTaskStatus401JSONResponse) VisitUpdateTaskStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTaskStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateTaskStatus404JSONResponse) VisitUpdateTaskStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTaskStatus500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateTaskStatus500JSONResponse) VisitUpdateTaskStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Health

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Approvals routed to the executive
	// (GET /api/v1/approvals)
	ListApprovals(ctx context.Context, request ListApprovalsRequestObject) (ListApprovalsResponseObject, error)
	// Approve or decline a pending approval (explicit, user-initiated)
	// (POST /api/v1/approvals/{approvalId}/decision)
	DecideApproval(ctx context.Context, request DecideApprovalRequestObject) (DecideApprovalResponseObject, error)
	// Ask a natural-language question about the network
	// (POST /api/v1/ask)
	PostAsk(ctx context.Context, request PostAskRequestObject) (PostAskResponseObject, error)
	// Exchange email and password for an access token
	// (POST /api/v1/auth/login)
	PostAuthLogin(ctx context.Context, request PostAuthLoginRequestObject) (PostAuthLoginResponseObject, error)
	// Revoke a refresh token
	// (POST /api/v1/auth/logout)
	PostAuthLogout(ctx context.Context, request PostAuthLogoutRequestObject) (PostAuthLogoutResponseObject, error)
	// The current authenticated user
	// (GET /api/v1/auth/me)
	GetAuthMe(ctx context.Context, request GetAuthMeRequestObject) (GetAuthMeResponseObject, error)
	// Confirm TOTP enrollment with a code
	// (POST /api/v1/auth/mfa/confirm)
	PostAuthMfaConfirm(ctx context.Context, request PostAuthMfaConfirmRequestObject) (PostAuthMfaConfirmResponseObject, error)
	// Begin TOTP enrollment (returns a secret + otpauth URI)
	// (POST /api/v1/auth/mfa/enroll)
	PostAuthMfaEnroll(ctx context.Context, request PostAuthMfaEnrollRequestObject) (PostAuthMfaEnrollResponseObject, error)
	// Rotate a refresh token into a new access + refresh token
	// (POST /api/v1/auth/refresh)
	PostAuthRefresh(ctx context.Context, request PostAuthRefreshRequestObject) (PostAuthRefreshResponseObject, error)
	// The AI-narrated Daily Brief over the current network
	// (GET /api/v1/brief)
	GetBrief(ctx context.Context, request GetBriefRequestObject) (GetBriefResponseObject, error)
	// List all facilities in the network
	// (GET /api/v1/facilities)
	ListFacilities(ctx context.Context, request ListFacilitiesRequestObject) (ListFacilitiesResponseObject, error)
	// Resolve a natural-language phrase to facilities via vector similarity
	// (GET /api/v1/facilities/search)
	SearchFacilities(ctx context.Context, request SearchFacilitiesRequestObject) (SearchFacilitiesResponseObject, error)
	// Facility drill-down (inventory, staff, alerts)
	// (GET /api/v1/facilities/{facilityId})
	GetFacility(ctx context.Context, request GetFacilityRequestObject) (GetFacilityResponseObject, error)
	// The current user's personalisation preferences
	// (GET /api/v1/me/preferences)
	GetMePreferences(ctx context.Context, request GetMePreferencesRequestObject) (GetMePreferencesResponseObject, error)
	// Update the current user's personalisation preferences
	// (PATCH /api/v1/me/preferences)
	UpdateMePreferences(ctx context.Context, request UpdateMePreferencesRequestObject) (UpdateMePreferencesResponseObject, error)
	// Deterministic network KPIs and weekly trends
	// (GET /api/v1/metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
	// The executive's "My Day" tasks
	// (GET /api/v1/tasks)
	ListTasks(ctx context.Context, request ListTasksRequestObject) (ListTasksResponseObject, error)
	// Update a task's status
	// (POST /api/v1/tasks/{taskId}/status)
	UpdateTaskStatus(ctx context.Context, request UpdateTaskStatusRequestObject) (UpdateTaskStatusResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListApprovals operation middleware
func (sh *strictHandler) ListApprovals(w http.ResponseWriter, r *http.Request) {
	var request ListApprovalsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListApprovals(ctx, request.(ListApprovalsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApprovals")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListApprovalsResponseObject); ok {
		if err := validResponse.VisitListApprovalsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DecideApproval operation middleware
func (sh *strictHandler) DecideApproval(w http.ResponseWriter, r *http.Request, approvalId string) {
	var request DecideApprovalRequestObject

	request.ApprovalId = approvalId

	var body DecideApprovalJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DecideApproval(ctx, request.(DecideApprovalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DecideApproval")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DecideApprovalResponseObject); ok {
		if err := validResponse.VisitDecideApprovalResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAsk operation middleware
func (sh *strictHandler) PostAsk(w http.ResponseWriter, r *http.Request) {
	var request PostAskRequestObject

	var body PostAskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAsk(ctx, request.(PostAskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAsk")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAskResponseObject); ok {
		if err := validResponse.VisitPostAskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogin operation middleware
func (sh *strictHandler) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLoginRequestObject

	var body PostAuthLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogin(ctx, request.(PostAuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLoginResponseObject); ok {
		if err := validResponse.VisitPostAuthLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogout operation middleware
func (sh *strictHandler) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLogoutRequestObject

	var body PostAuthLogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogout(ctx, request.(PostAuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLogoutResponseObject); ok {
		if err := validResponse.VisitPostAuthLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMe operation middleware
func (sh *strictHandler) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMe(ctx, request.(GetAuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMeResponseObject); ok {
		if err := validResponse.VisitGetAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthMfaConfirm operation middleware
func (sh *strictHandler) PostAuthMfaConfirm(w http.ResponseWriter, r *http.Request) {
	var request PostAuthMfaConfirmRequestObject

	var body PostAuthMfaConfirmJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthMfaConfirm(ctx, request.(PostAuthMfaConfirmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthMfaConfirm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthMfaConfirmResponseObject); ok {
		if err := validResponse.VisitPostAuthMfaConfirmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthMfaEnroll operation middleware
func (sh *strictHandler) PostAuthMfaEnroll(w http.ResponseWriter, r *http.Request) {
	var request PostAuthMfaEnrollRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthMfaEnroll(ctx, request.(PostAuthMfaEnrollRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthMfaEnroll")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthMfaEnrollResponseObject); ok {
		if err := validResponse.VisitPostAuthMfaEnrollResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthRefresh operation middleware
func (sh *strictHandler) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	var request PostAuthRefreshRequestObject

	var body PostAuthRefreshJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthRefresh(ctx, request.(PostAuthRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthRefresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthRefreshResponseObject); ok {
		if err := validResponse.VisitPostAuthRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBrief operation middleware
func (sh *strictHandler) GetBrief(w http.ResponseWriter, r *http.Request) {
	var request GetBriefRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBrief(ctx, request.(GetBriefRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBrief")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBriefResponseObject); ok {
		if err := validResponse.VisitGetBriefResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFacilities operation middleware
func (sh *strictHandler) ListFacilities(w http.ResponseWriter, r *http.Request) {
	var request ListFacilitiesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFacilities(ctx, request.(ListFacilitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFacilities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFacilitiesResponseObject); ok {
		if err := validResponse.VisitListFacilitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchFacilities operation middleware
func (sh *strictHandler) SearchFacilities(w http.ResponseWriter, r *http.Request, params SearchFacilitiesParams) {
	var request SearchFacilitiesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchFacilities(ctx, request.(SearchFacilitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchFacilities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchFacilitiesResponseObject); ok {
		if err := validResponse.VisitSearchFacilitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFacility operation middleware
func (sh *strictHandler) GetFacility(w http.ResponseWriter, r *http.Request, facilityId string) {
	var request GetFacilityRequestObject

	request.FacilityId = facilityId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFacility(ctx, request.(GetFacilityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFacility")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFacilityResponseObject); ok {
		if err := validResponse.VisitGetFacilityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMePreferences operation middleware
func (sh *strictHandler) GetMePreferences(w http.ResponseWriter, r *http.Request) {
	var request GetMePreferencesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMePreferences(ctx, request.(GetMePreferencesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMePreferences")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMePreferencesResponseObject); ok {
		if err := validResponse.VisitGetMePreferencesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMePreferences operation middleware
func (sh *strictHandler) UpdateMePreferences(w http.ResponseWriter, r *http.Request) {
	var request UpdateMePreferencesRequestObject

	var body UpdateMePreferencesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMePreferences(ctx, request.(UpdateMePreferencesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMePreferences")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMePreferencesResponseObject); ok {
		if err := validResponse.VisitUpdateMePreferencesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTasks operation middleware
func (sh *strictHandler) ListTasks(w http.ResponseWriter, r *http.Request) {
	var request ListTasksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTasks(ctx, request.(ListTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTasks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTasksResponseObject); ok {
		if err := validResponse.VisitListTasksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTaskStatus operation middleware
func (sh *strictHandler) UpdateTaskStatus(w http.ResponseWriter, r *http.Request, taskId string) {
	var request UpdateTaskStatusRequestObject

	request.TaskId = taskId

	var body UpdateTaskStatusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTaskStatus(ctx, request.(UpdateTaskStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTaskStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTaskStatusResponseObject); ok {
		if err := validResponse.VisitUpdateTaskStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fxfc9s2Ev8qGN7NNJnSltOkN3O6JyeOW0/jnsd2ntqMChErEhUIsAAoWc3ou9/gDylSBCXKtezeUy0J",
	"WCx++xe723yNEpEXggPXKhp/jSSoQnAF9sN7TG7hjxKUNp8SwTVw+ycuCkYTrKngo9+V4OY7lWSQY/PX",
	"PyXMonH0j9GG9Mj9qkYfpRQyWq/XcURAJZIWhkg0ju4zQNIdhpZYoRyzmZA5ECQkonyBGSXROo4+CD5j",
	"NHk2jpQoZQKIKkQ5wijxx1OeIqWxBsPTpZBTSgjw52GqkJQntMDMcMWFRpgxsQSCtEAFSAMb0hlVCCd2",
	"1zqOrrgGyTFzdI/OZXUcUiAXIBG4hXH0s9CXouTk+CzcVpIzAM3smes4+sxxqTMh6Z/wDDyclzoDrj1V",
	"q95UOo2eYcqARGaPJ2NOOWcg9ZWG3HwopChAaupskYDGlJm/9KqAaBwpLSlPzaUoCX6tYAGS6tU+9i9x",
	"QhnVqzuNdansTvdXiKimmkH4F/tF54d1HFX3jsa/GF790gaDFdn65C8VuUhMf4dEG/rnXC1BdoFJqLbw",
	"2g9UQ652sBdhKfHKfoYHvZ9duyrITVFIscCsyw/ORcn1pAAFSydVY5BYR+OIcv2vd1FNjXINKVi7sHoY",
	"ZCiOEglYA5lg3SJGsIYTTXPYENzsIZBQ8og9igo+4UKHRTzzmjLp0bier71bBzKZrsKaWusb8DI3uBfA",
	"ifkxNmYpxQKM2hBIGOVAGgI5RDEr2gkuqMYsiqOMSoOEBCEJyADZHcrbxCLeFvpGoVt3r2/aEuou9fpE",
	"XezdUjH/a1vld9l4ra4dS9i64oZ0kC01byQEbabs19T5zZzyT8BTnUXjN/tArfcFDyx1dgdKebrtEyXM",
	"JKhsosXchd6u6Ht/KZXzJTtBK3X22azreAVLNt5iwBPtu8ZnFfJejzQpjvOwskvBWsoOD5CUmi5aKptj",
	"jtPBCm/P8pRDl3svqcGwE7Cw8yIt5xPyOylwkAd7uD68KmsYZBaWdRtvAxEiFwTCAbeQQg2Ndf7WbktF",
	"tOKzF85wDgAPBcMcV1Z2sH/OABPjQZ86XSjT1Pk4l3AeFIm3MGvkBG0PW/MewuzCh65e51TFtqZp+Miy",
	"CSzBuNITDLfYrumHuKuT7i1pVl/vJu2WhehWkuiSngLpZB5vvwtmHgc7GEj71G8Txg/THy2WfKA1Vb7I",
	"MeG3xu6+O7PH6tSLOo3eCqkm8z4gntaJesBxzBpyGYKEFQNfANdCrgazcFXt6GNDaTybDSZ3Z1ZfQz51",
	"arHTSOsLNvmuDowrLHeJIZzXeLr+0yC2mxgO4dnQ3sXYNdZJ1h+mrw60FpUICc4BNR+GH4SiHJCiOWXY",
	"uDtEOfrlLH7z5T/oja01EPduZKfGEdYBUZRT1oiGvHTi6hHPVcNiHCO7bn4HWCbZLaiSOUNoI5AbYB4h",
	"GAdoQD3/KEGu9pu9WxbX5++8Qu2Att7hVydYKVDKvL0Lk2xQwTFDGWCmM6Royh3SVWhIhTDYLS3vJlmn",
	"VhjBAPGjJdIFrPGoecB5wSzL82hfyrXDh7UtvvsQxhpSIcNPLIJXaiJmE6VFMm9nWT1KdXhosLQnDBYu",
	"bRoQfOwOUeoJzXPKfSHGL5sKwQDznXGgvnL78BDhEKA/FTQAYyml52QARgSYxpMiGbyeSkj0ViZSFiYJ",
	"caFsxlpPwkbyRtMM5ISqyRS0BhmCKo7mEJY/w9PeZBYWVJRq4AUUyEP88zVoSZMbQbkOOYGSU91+91cP",
	"aGukRsTmYb3/pWLuXd3Skw1AFtfSbdy7KcSmgOq7hlTnk0hpf7qZCBI2Ecj7ingFVmopJBmQEFoajR0h",
	"/pq4P/5ptsCshEGKsZ0PO4Juf5C/Gf4g+IzK/HAQFSQSBhTv/LrYUerh4iOXgrEcQjgJXeBSZ5NS0qdh",
	"pEkwxM/PoJdCzp3wAkEYGx8+SHLzgg43UuMH9xaG7NGecIj3GwkzkMATCDCuMwkqE8w9SzAh1IXgm3aW",
	"td/9dI61MRrIJN9g9sin5zaluMl16Ma3rvzTq8D76lNb57eXhw5s5uhd3dBaWlQnkqq/GOIZTYwgJ/BQ",
	"UJdQ7FW4vRWpHc/FA4tQjTLq1qVDoN1jh8a2JZmsD8hEiycsuve2aEgJk8Fe95E1wUJSURVwqnjKxNLk",
	"zkBomfuAGEwuXK+suTPHvLRF8qkt7/lXXXhzp3yvBRH2cTgppEglKBtlRU+Jpa90H6y++7p6fdmGMvhL",
	"7C2uG40IP0A1VvPhbtNq1j6v4kj2seFeLL0e5K8hO/Rlsbb1h5noPpxuP97do/ObKzQTEukM0A80zTHn",
	"6GNVVkYfRDIvqD5FHwTXEif6ZEal0mO3XFQdYJP0yxlOQCHMif3xflXAnT0MJYwC1whLQHU1GM2k8H3s",
	"GWWAXv2W4/nm999en6ILYbu7GebkBAjVjc0m5J/+ymuNGUe9rJsLmlwFpKsQRmenb07PjIREARybN0L0",
	"9vTs9K3NuXRm5THCBR0t3oxarZjUJQP1E/OKROPIaNp5vSpuT1h8d3b2ZG3oVs+oZ3Rgw+46jt6dvemj",
	"WTM5anXM13H0veN496b2uIFtcpd5jk0oqVtbCklRaje1YNSh2anQOFVb3ShDpAP66Gv15xVZj5pF3kKo",
	"gCwubFu0boYZeUqcgwZpjvsaUYOTkXEVccbR5oCoaU5alhA3BLNtel/q1t97QVZPJuPtQve6beSGq/Uz",
	"qFifevm2c61mj9ayd2dv92/ajN3YHe/276jHT+yGf+/fUE8bPZ3mAxIS+Y4Dwsh3umvI0Ct4MOKhOkal",
	"AnlCOdXU+LTXAwzDpzpB5b8RSp+reXQczWy0hp9bKd1gSI9KptII3OikX/Zifk/NEUYc61JidsIwT0uc",
	"Aqra3whPRamtJ+TuFdgUt8ltW4IudTZiIqV8j7xLndlSxZGk3iqDPLfcG7MBu4evgCBVLXyU+FuC/PiQ",
	"ZJingGwhxqYzVSnG5kmYI5wkoBSq5gJqMZY6C8tRlHqQIM2640hy6zE7SJbvuhnjJ5GmQJDhs43aLSzE",
	"3Dg8/8wdCo57VQYzqx/AwnIN0ZG1zA+BhDOqlprZCZAn0DFD2ZcqQyfsR22GR4mrr+3Xq00t7ki61S32",
	"PVa9ri/PEdiKXZUnDPDKjTHmF/P+/v7o/r/3N/4GuRHukurMjhUTGCZVt3eQUF1p85jG0a6fBixk8yvy",
	"RdAXk8B7SCnv4P9Kgi4lVwh7BtG3yFdp0efbq9f7heL92X6JeA/7N/LfzxaLb4V+6ijsSG7HE0S5FibN",
	"gmUVhL89IOJMq1G2vnjz3hfDjgakO6An1lxgylbIL3kCkzA0z69OOJauaNKgj8QCXMmnCkPdrNSh1QKw",
	"PcHRWw+53Cw7IpatYZMeSBsMPwWi5iiEGWvQRZT3ZPXNkZQwiCNlhzJ6sXQzGy00QxWNaobClzT+2FnJ",
	"2DO7GybJaG47rhsyBGa4ZDoafx9HOX6geZlH4+/OYkPffXjTnQhwZZMjq0N70CXkrTCfA6lEuELV6MmL",
	"ha5bUIItIPR8LDKJFSAtmhq3oBgtINFCNkaMDlO8r5shovUuh3i5GQXbX0trDSYdWEs7slL4ucDdXmKF",
	"fIvn8WWtA4tUf1l1LmvOJWXshIglR6/qob0Y2Zm9GLmRvdcDdCSHUdHu9PapxjU0W8JHlGHzmIAAWz+/",
	"lAk3H3TmCfeNQgVIJThmVLn/PaxooVXJIYfoix0P8XOJbZg/FwRr6CL99PllB+TnSy73yNdhQFr4vZic",
	"HTOtxOlwcbfMrR5r6Lezal7haBLYmksJCMGvQD/dXPkOnwROniapujBBxaQNStOkyqM2Jy0B5mxVHdiE",
	"0nHbwrPu8Pbmpvd2xRHBrNvPPcHGsfiinqruxX2j0K/R9Qpd4NWvkedsg7DvbXfwHX01/7ki69GmgR1+",
	"Gztz2XTCB6URjvjfoR3XbeE/s2t0IwhhPSq9X9R+TOH/JGPxHhRbvr9RqB7vCGmdm+D+c5d7/NEvOaIU",
	"/Ah4QA53IBfU/fMBjtVV58G4AA5KoUKKabMEqFZKQ26u6YZuF5VBbB2AczgRkqaUo1d2GUFTyKifsbi7",
	"OUcjO8GRYg1LvDIpXilZNI5G0frL+n8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
