// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xcreativs/gigmann/internal/ports (interfaces: FacilityRepository,Narrator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks github.com/xcreativs/gigmann/internal/ports FacilityRepository,Narrator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	brief "github.com/xcreativs/gigmann/internal/core/brief"
	facility "github.com/xcreativs/gigmann/internal/core/facility"
	intel "github.com/xcreativs/gigmann/internal/intel"
	gomock "go.uber.org/mock/gomock"
)

// MockFacilityRepository is a mock of FacilityRepository interface.
type MockFacilityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFacilityRepositoryMockRecorder
	isgomock struct{}
}

// MockFacilityRepositoryMockRecorder is the mock recorder for MockFacilityRepository.
type MockFacilityRepositoryMockRecorder struct {
	mock *MockFacilityRepository
}

// NewMockFacilityRepository creates a new mock instance.
func NewMockFacilityRepository(ctrl *gomock.Controller) *MockFacilityRepository {
	mock := &MockFacilityRepository{ctrl: ctrl}
	mock.recorder = &MockFacilityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacilityRepository) EXPECT() *MockFacilityRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockFacilityRepository) List(ctx context.Context) ([]facility.Facility, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]facility.Facility)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFacilityRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFacilityRepository)(nil).List), ctx)
}

// MockNarrator is a mock of Narrator interface.
type MockNarrator struct {
	ctrl     *gomock.Controller
	recorder *MockNarratorMockRecorder
	isgomock struct{}
}

// MockNarratorMockRecorder is the mock recorder for MockNarrator.
type MockNarratorMockRecorder struct {
	mock *MockNarrator
}

// NewMockNarrator creates a new mock instance.
func NewMockNarrator(ctrl *gomock.Controller) *MockNarrator {
	mock := &MockNarrator{ctrl: ctrl}
	mock.recorder = &MockNarratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNarrator) EXPECT() *MockNarratorMockRecorder {
	return m.recorder
}

// NarrateBrief mocks base method.
func (m *MockNarrator) NarrateBrief(ctx context.Context, c intel.Context) (brief.Brief, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NarrateBrief", ctx, c)
	ret0, _ := ret[0].(brief.Brief)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NarrateBrief indicates an expected call of NarrateBrief.
func (mr *MockNarratorMockRecorder) NarrateBrief(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NarrateBrief", reflect.TypeOf((*MockNarrator)(nil).NarrateBrief), ctx, c)
}
