// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xcreativs/gigmann/internal/ports (interfaces: FacilityRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks github.com/xcreativs/gigmann/internal/ports FacilityRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	facility "github.com/xcreativs/gigmann/internal/core/facility"
	gomock "go.uber.org/mock/gomock"
)

// MockFacilityRepository is a mock of FacilityRepository interface.
type MockFacilityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFacilityRepositoryMockRecorder
	isgomock struct{}
}

// MockFacilityRepositoryMockRecorder is the mock recorder for MockFacilityRepository.
type MockFacilityRepositoryMockRecorder struct {
	mock *MockFacilityRepository
}

// NewMockFacilityRepository creates a new mock instance.
func NewMockFacilityRepository(ctrl *gomock.Controller) *MockFacilityRepository {
	mock := &MockFacilityRepository{ctrl: ctrl}
	mock.recorder = &MockFacilityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacilityRepository) EXPECT() *MockFacilityRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockFacilityRepository) List(ctx context.Context) ([]facility.Facility, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]facility.Facility)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFacilityRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFacilityRepository)(nil).List), ctx)
}
