// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xcreativs/gigmann/internal/ports (interfaces: FacilityRepository,Narrator,BriefGenerator,UserRepository,PasswordHasher,TokenService,RefreshTokenStore,ApprovalRepository,TaskRepository,Answerer,QuestionAnswerer,AuditLogger)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks github.com/xcreativs/gigmann/internal/ports FacilityRepository,Narrator,BriefGenerator,UserRepository,PasswordHasher,TokenService,RefreshTokenStore,ApprovalRepository,TaskRepository,Answerer,QuestionAnswerer,AuditLogger
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	approval "github.com/xcreativs/gigmann/internal/core/approval"
	auth "github.com/xcreativs/gigmann/internal/core/auth"
	brief "github.com/xcreativs/gigmann/internal/core/brief"
	facility "github.com/xcreativs/gigmann/internal/core/facility"
	task "github.com/xcreativs/gigmann/internal/core/task"
	intel "github.com/xcreativs/gigmann/internal/intel"
	ports "github.com/xcreativs/gigmann/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockFacilityRepository is a mock of FacilityRepository interface.
type MockFacilityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFacilityRepositoryMockRecorder
	isgomock struct{}
}

// MockFacilityRepositoryMockRecorder is the mock recorder for MockFacilityRepository.
type MockFacilityRepositoryMockRecorder struct {
	mock *MockFacilityRepository
}

// NewMockFacilityRepository creates a new mock instance.
func NewMockFacilityRepository(ctrl *gomock.Controller) *MockFacilityRepository {
	mock := &MockFacilityRepository{ctrl: ctrl}
	mock.recorder = &MockFacilityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacilityRepository) EXPECT() *MockFacilityRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockFacilityRepository) List(ctx context.Context) ([]facility.Facility, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]facility.Facility)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFacilityRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFacilityRepository)(nil).List), ctx)
}

// MockNarrator is a mock of Narrator interface.
type MockNarrator struct {
	ctrl     *gomock.Controller
	recorder *MockNarratorMockRecorder
	isgomock struct{}
}

// MockNarratorMockRecorder is the mock recorder for MockNarrator.
type MockNarratorMockRecorder struct {
	mock *MockNarrator
}

// NewMockNarrator creates a new mock instance.
func NewMockNarrator(ctrl *gomock.Controller) *MockNarrator {
	mock := &MockNarrator{ctrl: ctrl}
	mock.recorder = &MockNarratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNarrator) EXPECT() *MockNarratorMockRecorder {
	return m.recorder
}

// NarrateBrief mocks base method.
func (m *MockNarrator) NarrateBrief(ctx context.Context, c intel.Context) (brief.Brief, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NarrateBrief", ctx, c)
	ret0, _ := ret[0].(brief.Brief)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NarrateBrief indicates an expected call of NarrateBrief.
func (mr *MockNarratorMockRecorder) NarrateBrief(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NarrateBrief", reflect.TypeOf((*MockNarrator)(nil).NarrateBrief), ctx, c)
}

// MockBriefGenerator is a mock of BriefGenerator interface.
type MockBriefGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockBriefGeneratorMockRecorder
	isgomock struct{}
}

// MockBriefGeneratorMockRecorder is the mock recorder for MockBriefGenerator.
type MockBriefGeneratorMockRecorder struct {
	mock *MockBriefGenerator
}

// NewMockBriefGenerator creates a new mock instance.
func NewMockBriefGenerator(ctrl *gomock.Controller) *MockBriefGenerator {
	mock := &MockBriefGenerator{ctrl: ctrl}
	mock.recorder = &MockBriefGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBriefGenerator) EXPECT() *MockBriefGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockBriefGenerator) Generate(ctx context.Context) (brief.Brief, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx)
	ret0, _ := ret[0].(brief.Brief)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockBriefGeneratorMockRecorder) Generate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockBriefGenerator)(nil).Generate), ctx)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(ctx context.Context, email string) (ports.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(ports.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx context.Context, id string) (ports.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(ports.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockUserRepository) Save(ctx context.Context, account ports.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserRepositoryMockRecorder) Save(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserRepository)(nil).Save), ctx, account)
}

// MockPasswordHasher is a mock of PasswordHasher interface.
type MockPasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHasherMockRecorder
	isgomock struct{}
}

// MockPasswordHasherMockRecorder is the mock recorder for MockPasswordHasher.
type MockPasswordHasherMockRecorder struct {
	mock *MockPasswordHasher
}

// NewMockPasswordHasher creates a new mock instance.
func NewMockPasswordHasher(ctrl *gomock.Controller) *MockPasswordHasher {
	mock := &MockPasswordHasher{ctrl: ctrl}
	mock.recorder = &MockPasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHasher) EXPECT() *MockPasswordHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockPasswordHasher) Hash(plain string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", plain)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPasswordHasherMockRecorder) Hash(plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPasswordHasher)(nil).Hash), plain)
}

// Verify mocks base method.
func (m *MockPasswordHasher) Verify(plain, encoded string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", plain, encoded)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockPasswordHasherMockRecorder) Verify(plain, encoded any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockPasswordHasher)(nil).Verify), plain, encoded)
}

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockTokenService) Issue(p auth.Principal) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", p)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockTokenServiceMockRecorder) Issue(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockTokenService)(nil).Issue), p)
}

// Verify mocks base method.
func (m *MockTokenService) Verify(token string) (auth.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", token)
	ret0, _ := ret[0].(auth.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockTokenServiceMockRecorder) Verify(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockTokenService)(nil).Verify), token)
}

// MockRefreshTokenStore is a mock of RefreshTokenStore interface.
type MockRefreshTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenStoreMockRecorder
	isgomock struct{}
}

// MockRefreshTokenStoreMockRecorder is the mock recorder for MockRefreshTokenStore.
type MockRefreshTokenStoreMockRecorder struct {
	mock *MockRefreshTokenStore
}

// NewMockRefreshTokenStore creates a new mock instance.
func NewMockRefreshTokenStore(ctrl *gomock.Controller) *MockRefreshTokenStore {
	mock := &MockRefreshTokenStore{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenStore) EXPECT() *MockRefreshTokenStoreMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockRefreshTokenStore) Consume(ctx context.Context, raw string) (auth.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, raw)
	ret0, _ := ret[0].(auth.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockRefreshTokenStoreMockRecorder) Consume(ctx, raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockRefreshTokenStore)(nil).Consume), ctx, raw)
}

// Issue mocks base method.
func (m *MockRefreshTokenStore) Issue(ctx context.Context, p auth.Principal, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", ctx, p, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockRefreshTokenStoreMockRecorder) Issue(ctx, p, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockRefreshTokenStore)(nil).Issue), ctx, p, ttl)
}

// Revoke mocks base method.
func (m *MockRefreshTokenStore) Revoke(ctx context.Context, raw string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, raw)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshTokenStoreMockRecorder) Revoke(ctx, raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshTokenStore)(nil).Revoke), ctx, raw)
}

// MockApprovalRepository is a mock of ApprovalRepository interface.
type MockApprovalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalRepositoryMockRecorder
	isgomock struct{}
}

// MockApprovalRepositoryMockRecorder is the mock recorder for MockApprovalRepository.
type MockApprovalRepositoryMockRecorder struct {
	mock *MockApprovalRepository
}

// NewMockApprovalRepository creates a new mock instance.
func NewMockApprovalRepository(ctrl *gomock.Controller) *MockApprovalRepository {
	mock := &MockApprovalRepository{ctrl: ctrl}
	mock.recorder = &MockApprovalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalRepository) EXPECT() *MockApprovalRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockApprovalRepository) Get(ctx context.Context, id string) (approval.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(approval.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApprovalRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApprovalRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockApprovalRepository) List(ctx context.Context) ([]approval.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]approval.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockApprovalRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApprovalRepository)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockApprovalRepository) Save(ctx context.Context, a approval.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockApprovalRepositoryMockRecorder) Save(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockApprovalRepository)(nil).Save), ctx, a)
}

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTaskRepository) Get(ctx context.Context, id string) (task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaskRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockTaskRepository) List(ctx context.Context) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTaskRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepository)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockTaskRepository) Save(ctx context.Context, t task.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTaskRepositoryMockRecorder) Save(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTaskRepository)(nil).Save), ctx, t)
}

// MockAnswerer is a mock of Answerer interface.
type MockAnswerer struct {
	ctrl     *gomock.Controller
	recorder *MockAnswererMockRecorder
	isgomock struct{}
}

// MockAnswererMockRecorder is the mock recorder for MockAnswerer.
type MockAnswererMockRecorder struct {
	mock *MockAnswerer
}

// NewMockAnswerer creates a new mock instance.
func NewMockAnswerer(ctrl *gomock.Controller) *MockAnswerer {
	mock := &MockAnswerer{ctrl: ctrl}
	mock.recorder = &MockAnswererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnswerer) EXPECT() *MockAnswererMockRecorder {
	return m.recorder
}

// Answer mocks base method.
func (m *MockAnswerer) Answer(ctx context.Context, question string, c intel.Context) (intel.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Answer", ctx, question, c)
	ret0, _ := ret[0].(intel.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Answer indicates an expected call of Answer.
func (mr *MockAnswererMockRecorder) Answer(ctx, question, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Answer", reflect.TypeOf((*MockAnswerer)(nil).Answer), ctx, question, c)
}

// MockQuestionAnswerer is a mock of QuestionAnswerer interface.
type MockQuestionAnswerer struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionAnswererMockRecorder
	isgomock struct{}
}

// MockQuestionAnswererMockRecorder is the mock recorder for MockQuestionAnswerer.
type MockQuestionAnswererMockRecorder struct {
	mock *MockQuestionAnswerer
}

// NewMockQuestionAnswerer creates a new mock instance.
func NewMockQuestionAnswerer(ctrl *gomock.Controller) *MockQuestionAnswerer {
	mock := &MockQuestionAnswerer{ctrl: ctrl}
	mock.recorder = &MockQuestionAnswererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionAnswerer) EXPECT() *MockQuestionAnswererMockRecorder {
	return m.recorder
}

// Answer mocks base method.
func (m *MockQuestionAnswerer) Answer(ctx context.Context, question string) (intel.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Answer", ctx, question)
	ret0, _ := ret[0].(intel.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Answer indicates an expected call of Answer.
func (mr *MockQuestionAnswererMockRecorder) Answer(ctx, question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Answer", reflect.TypeOf((*MockQuestionAnswerer)(nil).Answer), ctx, question)
}

// MockAuditLogger is a mock of AuditLogger interface.
type MockAuditLogger struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLoggerMockRecorder
	isgomock struct{}
}

// MockAuditLoggerMockRecorder is the mock recorder for MockAuditLogger.
type MockAuditLoggerMockRecorder struct {
	mock *MockAuditLogger
}

// NewMockAuditLogger creates a new mock instance.
func NewMockAuditLogger(ctrl *gomock.Controller) *MockAuditLogger {
	mock := &MockAuditLogger{ctrl: ctrl}
	mock.recorder = &MockAuditLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogger) EXPECT() *MockAuditLoggerMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockAuditLogger) Record(ctx context.Context, e ports.AuditEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", ctx, e)
}

// Record indicates an expected call of Record.
func (mr *MockAuditLoggerMockRecorder) Record(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockAuditLogger)(nil).Record), ctx, e)
}
